version: '3.7'

services:

  mongo:
    image: mongo
    container_name: my-mongodb
    restart: always   
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: my-mongo-express
    restart: always    
    ports:
      - 8585:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo  
    links: 
      - mongo
    