version: '3.7'

services:

  mongo:
    image: mongo
    container_name: my-mongodb
    restart: always   
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: my-mongo-express
    restart: always    
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo  
    links: 
      - mongo
  redis:
    image: redis    
    container_name: my_redis-server
    restart: on-failure
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis_data_volume:/data
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: my_redisinsight
    restart: on-failure
    ports:
      - 8008:8001
    volumes:
      - redisinsight:/db
volumes:
  redis_data_volume:
  redisinsight:    